url: https://www.shjensecurities.tech
baseurl: ""

# Site settings
title: Shjen Securities
seo_title: "Shjen Securities | Cybersecurity for Steamboat Springs, CO"
email: info@shjensecurities.tech
description: "Shjen Securities provides network hardening, password management, and IT infrastructure for homes and small businesses in Steamboat Springs, CO."


# Team names, titles and social links
people:
- name: Ayric Ingram
  pic: 2
  position: C.E.O.
  social:
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 322 Riverview Way Apt. 211
  - line: Steamboat Springs, CO 80487

# Build settings
markdown: kramdown
permalink: pretty
